// Player-made learning games: create, test, publish, replay, and remove locally.
(() => {
  const icons=['🎮','⚔️','🏰','🚀','🐉','🧠','⭐','🧩'];
  const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ensure=()=>{Player.data.createdGames||=[]};
  let draft=null,session=null;
  const validRounds=value=>[5,10,15,20].includes(Number(value))?Number(value):5;
  const banks={
    Geography:[['What is the largest ocean?',['Pacific Ocean','Atlantic Ocean','Indian Ocean','Arctic Ocean'],'Pacific Ocean'],['Which continent is Egypt in?',['Africa','Asia','Europe','South America'],'Africa'],['What is the capital of France?',['Paris','Rome','Madrid','Berlin'],'Paris'],['Which country has the maple leaf flag?',['Canada','Japan','Brazil','India'],'Canada'],['Mount Everest is in which mountain range?',['Himalayas','Andes','Alps','Rockies'],'Himalayas'],['Which is the largest continent?',['Asia','Africa','Europe','Australia'],'Asia'],['The Amazon rainforest is mostly in which country?',['Brazil','Mexico','Peru','Spain'],'Brazil'],['What is the capital of Japan?',['Tokyo','Seoul','Beijing','Bangkok'],'Tokyo']],
    Science:[['Which planet is known as the Red Planet?',['Mars','Venus','Jupiter','Mercury'],'Mars'],['What gas do plants absorb?',['Carbon dioxide','Oxygen','Helium','Hydrogen'],'Carbon dioxide'],['What force pulls objects toward Earth?',['Gravity','Magnetism','Friction','Electricity'],'Gravity'],['Water freezes at what temperature in Celsius?',['0°C','10°C','32°C','100°C'],'0°C'],['Which organ pumps blood around the body?',['Heart','Lungs','Brain','Stomach'],'Heart'],['What is the center of an atom called?',['Nucleus','Cell','Orbit','Crystal'],'Nucleus'],['Which state of matter has a fixed shape?',['Solid','Liquid','Gas','Plasma'],'Solid'],['Earth travels around which star?',['The Sun','Polaris','Sirius','Vega'],'The Sun']]
  };
  const makeQuestion=game=>{
    game.subject||='Math';
    if(banks[game.subject]){const item=banks[game.subject][Math.floor(Math.random()*banks[game.subject].length)];return{text:item[0],options:[...item[1]].sort(()=>Math.random()-.5),answer:item[2]}}
    const max={Easy:10,Normal:25,Hard:60}[game.difficulty]||25;
    if(game.subject==='Geometry'){const a=2+Math.floor(Math.random()*Math.min(max,18)),b=2+Math.floor(Math.random()*Math.min(max,18)),rectangleArea=a*b,squareArea=a*a;const choices=(answer,step=2)=>[answer,answer+step,Math.max(1,answer-step),answer+step*2].filter((x,i,list)=>list.indexOf(x)===i).sort(()=>Math.random()-.5);const measured=(kind,x,y='')=>`<div class="geometry-visual"><svg viewBox="0 0 260 170" role="img" aria-label="${kind} diagram">${kind==='rectangle'?'<rect x="45" y="35" width="170" height="100" rx="3"/>':kind==='square'?'<rect x="70" y="25" width="120" height="120" rx="3"/>':''}${x?`<text x="130" y="163">${x} cm</text>`:''}${y?`<text class="vertical-label" x="232" y="88">${y} cm</text>`:''}</svg></div>`;const polygon=(points,label)=>`<div class="geometry-visual"><svg viewBox="0 0 260 170" role="img" aria-label="${label}"><polygon points="${points}"/></svg></div>`;const items=[{text:'What is the area of this rectangle?',visual:measured('rectangle',a,b),answer:rectangleArea,options:choices(rectangleArea,a),unit:' cm²'},{text:'What is the area of this square?',visual:measured('square',a),answer:squareArea,options:choices(squareArea,a),unit:' cm²'},{text:'What is the perimeter of this rectangle?',visual:measured('rectangle',a,b),answer:2*(a+b),options:choices(2*(a+b),2),unit:' cm'},{text:'What is the perimeter of this square?',visual:measured('square',a),answer:4*a,options:choices(4*a,4),unit:' cm'},{text:'How many sides does this triangle have?',visual:polygon('130,22 225,145 35,145','triangle'),answer:3,options:choices(3,1)},{text:'How many sides does this hexagon have?',visual:polygon('75,25 185,25 230,85 185,145 75,145 30,85','hexagon'),answer:6,options:choices(6,1)},{text:'How many degrees are in this right angle?',visual:`<div class="geometry-visual"><svg viewBox="0 0 260 170" role="img" aria-label="right angle"><polyline points="55,140 55,40 210,40"/><rect class="angle-mark" x="55" y="40" width="30" height="30"/></svg></div>`,answer:90,options:[45,90,180,360],unit:'°'},{text:'How many vertices does this rectangle have?',visual:measured('rectangle','',''),answer:4,options:choices(4,1)},{text:'How many equal sides does this square have?',visual:measured('square','',''),answer:4,options:choices(4,1)},{text:'How many sides does this octagon have?',visual:polygon('85,20 175,20 235,65 235,105 175,150 85,150 25,105 25,65','octagon'),answer:8,options:choices(8,1)}];return items[Math.floor(Math.random()*items.length)]}
    const operation=game.operation==='Mixed'?['Addition','Subtraction','Multiplication'][Math.floor(Math.random()*3)]:game.operation;let a=1+Math.floor(Math.random()*max),b=1+Math.floor(Math.random()*max),answer,symbol;
    if(operation==='Addition'){answer=a+b;symbol='+'} if(operation==='Subtraction'){if(b>a)[a,b]=[b,a];answer=a-b;symbol='−'} if(operation==='Multiplication'){a=1+Math.floor(Math.random()*Math.min(12,max));b=1+Math.floor(Math.random()*Math.min(12,max));answer=a*b;symbol='×'} return{text:`${a} ${symbol} ${b} = ?`,answer};
  };
  const section=()=>{ensure();const cards=Player.data.createdGames.map(g=>`<article class="game-card card created-game-card" onclick="CreatedGames.play('${g.id}')"><div class="emoji">${g.icon}</div><h3>${esc(g.name)}</h3><p>${g.subject||'Math'} · ${g.difficulty} · ${validRounds(g.rounds)} rounds</p><span class="go">→</span></article>`).join('');return`<section class="created-games-section"><div class="section-title"><div><p class="eyebrow">Made by you</p><h2>Created Games</h2></div><button class="btn gold" onclick="CreatedGames.openCreator()">＋ Create Game</button></div><div class="game-grid created-games-grid">${cards||'<div class="created-empty card"><span>🎨</span><div><h3>Create your first game</h3><p>Build it, test it, then publish it here.</p></div><button class="btn green" onclick="CreatedGames.openCreator()">Start Creating</button></div>'}</div></section>`};
  const oldHome=App.home.bind(App),oldGames=App.games.bind(App),oldRender=App.render.bind(App);App.home=function(){return oldHome()+section()};App.games=function(){return oldGames()+section()};App.render=function(){if(!['create-game','created-game'].includes(this.current))return oldRender();document.querySelector('#screen').className='screen';document.querySelector('#screen').innerHTML=this.current==='create-game'?CreatedGames.renderCreator():CreatedGames.renderGame();this.bind();this.hud()};
  window.CreatedGames={
    openCreator(){draft={name:'My Learning Quest',icon:'🎮',subject:'Math',operation:'Mixed',difficulty:'Normal',rounds:5};App.current='create-game';App.render()},edit(){draft={...session.game};App.current='create-game';App.render()},update(field,value){draft[field]=field==='rounds'?validRounds(value):value;if(['icon','subject','rounds'].includes(field))App.render()},
    renderCreator(){draft||={name:'My Learning Quest',icon:'🎮',subject:'Math',operation:'Mixed',difficulty:'Normal',rounds:5};return`<div class="page-head"><div><p class="eyebrow">Game Creator</p><h1>🎨 Create a Game</h1></div><button class="btn ghost" data-page="games">Cancel</button></div><section class="creator-layout"><form class="creator-form card" onsubmit="event.preventDefault();CreatedGames.test()"><label>Game name<input class="text-input" maxlength="28" required value="${esc(draft.name)}" oninput="CreatedGames.update('name',this.value)"></label><label>Choose an icon<div class="icon-picker">${icons.map(i=>`<button type="button" class="${draft.icon===i?'selected':''}" onclick="CreatedGames.update('icon','${i}')">${i}</button>`).join('')}</div></label><label>Subject<select class="text-input" onchange="CreatedGames.update('subject',this.value)">${['Math','Geometry','Geography','Science'].map(x=>`<option ${draft.subject===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="creator-difficulty">Difficulty<select class="text-input" onchange="CreatedGames.update('difficulty',this.value)">${['Easy','Normal','Hard'].map(x=>`<option ${draft.difficulty===x?'selected':''}>${x}</option>`).join('')}</select></label>${draft.subject==='Math'?`<label>Math type<select class="text-input" onchange="CreatedGames.update('operation',this.value)">${['Mixed','Addition','Subtraction','Multiplication'].map(x=>`<option ${draft.operation===x?'selected':''}>${x}</option>`).join('')}</select></label>`:''}<label class="creator-round-count">Number of rounds<select class="text-input" onchange="CreatedGames.update('rounds',this.value)">${[5,10,15,20].map(n=>`<option value="${n}" ${validRounds(draft.rounds)===n?'selected':''}>${n} rounds</option>`).join('')}</select></label><div class="creator-rounds"><b>${validRounds(draft.rounds)} rounds</b><span>Choose how many questions players answer.</span></div><button class="btn gold">▶ Test My Game</button></form><article class="game-card card created-preview"><div class="emoji">${draft.icon}</div><h3>${esc(draft.name||'Untitled Game')}</h3><p>${draft.subject} · ${draft.difficulty} · ${validRounds(draft.rounds)} rounds</p><span class="preview-label">Preview</span></article></section>`},
    test(){if(!draft.name.trim())return Rewards.toast('Please name your game.');session={game:{...draft,name:draft.name.trim(),rounds:validRounds(draft.rounds)},round:1,score:0,test:true};session.q=makeQuestion(session.game);App.current='created-game';App.render()},play(id){ensure();const savedGame=Player.data.createdGames.find(g=>g.id===id);if(!savedGame)return;const game={...savedGame,rounds:validRounds(savedGame.rounds)};session={game,round:1,score:0,q:makeQuestion(game),test:false};App.current='created-game';App.render()},answer(event){event.preventDefault();this.choose(event.target.elements.answer.value)},
    choose(value){const correct=String(value).trim().toLowerCase()===String(session.q.answer).trim().toLowerCase();if(correct){session.score++;Rewards.toast('✅ Correct!')}else Rewards.toast(`The answer was ${session.q.answer}.`);if(session.round>=session.game.rounds)session.finished=true;else{session.round++;session.q=makeQuestion(session.game)}App.render()},publish(){ensure();const game={...session.game,id:`game-${Date.now()}`,createdAt:new Date().toISOString()};Player.data.createdGames.push(game);Player.save();session.game=game;session.test=false;App.render();Rewards.toast('🎉 Published to Created Games!')},remove(){if(!session?.game?.id)return;Player.data.createdGames=Player.data.createdGames.filter(g=>g.id!==session.game.id);Player.save();App.navigate('games');Rewards.toast('Created game removed.')},replay(){session.round=1;session.score=0;session.finished=false;session.q=makeQuestion(session.game);App.render()},selectOption(index){this.choose(session.q.options[index])},
    renderGame(){if(!session)return'<button class="btn" data-page="games">Back to Games</button>';const s=session;if(s.finished)return`<section class="created-result card"><div class="big-game-icon">${s.game.icon}</div><p class="eyebrow">Game complete</p><h1>${esc(s.game.name)}</h1><div class="created-score">${s.score} / ${s.game.rounds}</div><p>${s.test?'Do you like your game? Publish it to add it to Created Games.':'Great playing!'}</p><div class="actions">${s.test?'<button class="btn ghost" onclick="CreatedGames.edit()">Edit It</button><button class="btn gold" onclick="CreatedGames.publish()">⭐ Publish to Created Games</button>':'<button class="btn green" onclick="CreatedGames.replay()">Play Again</button><button class="btn red" onclick="CreatedGames.remove()">Delete Game</button>'}<button class="btn ghost" data-page="games">Games</button></div></section>`;const answer=s.q.options?`<div class="created-options">${s.q.options.map((o,i)=>`<button onclick="CreatedGames.selectOption(${i})">${esc(o)}${s.q.unit||''}</button>`).join('')}</div>`:`<form class="answer-row" onsubmit="CreatedGames.answer(event)"><input name="answer" inputmode="numeric" autocomplete="off" required autofocus><button class="btn gold">Check</button></form>`;return`<section class="game-shell card created-play"><div class="game-hud"><button class="btn ghost" data-page="games">← Games</button><h2>${s.game.icon} ${esc(s.game.name)}</h2><b>Round ${s.round}/${s.game.rounds} · ⭐ ${s.score}</b></div><div class="question-panel"><p class="eyebrow">${s.game.subject||'Math'} · ${s.game.difficulty}</p><div class="question created-question">${esc(s.q.text)}</div>${s.q.visual||''}${answer}</div></section>`}
  };ensure();App.render();
})();
