// Infinite Academy foundation: deterministic worlds, creator codes, branching
// adventures, skill trees, collections, accessibility, and portable saves.
(() => {
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=value=>JSON.parse(JSON.stringify(value));
  const fresh=()=>({version:1,skillPoints:3,skills:{power:0,wisdom:0,luck:0,heart:0},stickers:[],cards:[],world:null,customLevels:[],seasonXp:0,house:'',reputation:0});
  const state=()=>{if(!Player.data.infiniteAcademy||Player.data.infiniteAcademy.version!==1)Player.data.infiniteAcademy=fresh();return Player.data.infiniteAcademy};
  const hash=text=>{let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const rng=seed=>()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);
  const pick=(r,list)=>list[Math.floor(r()*list.length)];
  const worlds={
    themes:[['Dinosaur Island','🦖'],['Robot City','🤖'],['Ocean Kingdom','🌊'],['Star Frontier','🚀'],['Mythic Mountains','🐲'],['Time Labyrinth','⌛'],['Candy Cosmos','🍭'],['Jungle Ruins','🌴']],
    weather:[['Sunny','☀️'],['Rainy','🌧️'],['Snowy','❄️'],['Meteor Shower','☄️'],['Magical Storm','⚡']],
    subjects:['Addition','Subtraction','Multiplication','Fractions','Patterns','Mixed'], bosses:[['Number Dragon','🐉'],['Quiz Titan','🗿'],['Logic Witch','🧙‍♀️'],['Fraction Kraken','🐙'],['Clockwork King','👑']],
    rewards:[['Ancient Sticker','🏺'],['Galaxy Card','🌌'],['Golden Badge','🏅'],['Pet Egg','🥚'],['Mystery Key','🗝️']]
  };
  const makeQuestion=(subject,r=Math.random)=>{let a=2+Math.floor(r()*11),b=2+Math.floor(r()*11);if(subject==='Subtraction')return{text:`${a+b} − ${a} = ?`,answer:String(b)};if(subject==='Multiplication')return{text:`${a} × ${b} = ?`,answer:String(a*b)};if(subject==='Fractions')return{text:'Which fraction equals one half?',answer:'2/4',options:['1/4','2/4','3/4']};if(subject==='Patterns')return{text:`Continue: ${a}, ${a+3}, ${a+6}, ?`,answer:String(a+9)};if(subject==='Mixed')return makeQuestion(pick(rng(hash(String(Date.now()))),worlds.subjects.slice(0,-1)),r);return{text:`${a} + ${b} = ?`,answer:String(a+b)}};
  const encode=data=>btoa(unescape(encodeURIComponent(JSON.stringify(data))));
  const decode=text=>JSON.parse(decodeURIComponent(escape(atob(text.trim()))));
  const save=(render=true)=>{Player.save();if(render)App.render()};
  const syncTheme=()=>{const a=Player.data.settings.accessibility||{};document.body.classList.toggle('large-game-text',!!a.largeText);document.body.classList.toggle('high-contrast',!!a.contrast);document.body.classList.toggle('calm-mode',!!a.calm);document.body.classList.toggle('dyslexia-font',!!a.dyslexia)};
  window.InfiniteAcademy={
    generate(seedText){const seed=(seedText||Math.random().toString(36).slice(2,8)).toUpperCase(),r=rng(hash(seed)),s=state();s.world={seed,theme:pick(r,worlds.themes),weather:pick(r,worlds.weather),subject:pick(r,worlds.subjects),boss:pick(r,worlds.bosses),reward:pick(r,worlds.rewards),room:1,hp:5,bossHp:5,path:[],q:null};s.world.q=makeQuestion(s.world.subject,r);App.current='infinite-world';save()},
    answer(value){const s=state(),w=s.world;if(!w)return;const correct=String(value).trim().toLowerCase()===w.q.answer.toLowerCase();w.path.push(correct?'victory':'practice');if(correct){w.bossHp--;s.reputation+=2;s.seasonXp+=10}else w.hp--;if(w.bossHp<=0)return this.worldWin();if(w.hp<=0){w.hp=5;w.bossHp=5;w.path=[];Rewards.toast('Your team recovered at camp. Try again!')}w.room++;const r=rng(hash(w.seed+w.room));w.q=makeQuestion(w.subject,r);save()},
    choose(choice){const w=state().world;w.path.push(choice);if(choice==='treasure')state().reputation++;else w.hp=Math.min(5,w.hp+1);w.room++;save()},
    worldWin(){const s=state(),w=s.world,name=w.reward[0];if(!s.stickers.includes(name))s.stickers.push(name);if(!s.cards.includes(w.boss[0]))s.cards.push(w.boss[0]);s.skillPoints++;Player.addRewards(150,90,2,2);CoolAcademy?.celebrate(`${w.reward[1]} ${name} unlocked!`);App.current='infinite-lab';save()},
    buySkill(id){const s=state(),cost=s.skills[id]+1;if(s.skillPoints<cost||s.skills[id]>=5)return;s.skillPoints-=cost;s.skills[id]++;save()},
    chooseHouse(id){const s=state();if(s.house&&!confirm('Change academy house? Your progress stays safe.'))return;s.house=id;s.reputation+=5;save()},
    creatorPreview(event){event.preventDefault();const f=new FormData(event.target),level={version:1,name:String(f.get('name')).slice(0,30),theme:f.get('theme'),subject:f.get('subject'),difficulty:f.get('difficulty'),rounds:Math.max(3,Math.min(20,Number(f.get('rounds'))||5)),reward:f.get('reward')};state().draft=level;state().shareCode=encode(level);save()},
    copyCode(){const code=state().shareCode||'';navigator.clipboard?.writeText(code);Rewards.toast('Level code copied!')},
    importLevel(event){event.preventDefault();try{const level=decode(new FormData(event.target).get('code'));if(level.version!==1||!level.name||!level.subject)throw Error();state().customLevels.push(level);state().draft=level;Rewards.toast(`${level.name} imported!`);save()}catch(_){Rewards.toast('That level code is not valid.')}},
    playCustom(){const level=state().draft;if(!level)return;const seed=`${level.name}-${level.subject}-${level.rounds}`;this.generate(seed);const w=state().world;w.theme=worlds.themes.find(x=>x[0]===level.theme)||worlds.themes[0];w.subject=level.subject;w.reward=worlds.rewards.find(x=>x[0]===level.reward)||worlds.rewards[0];w.customName=level.name;w.bossHp=level.rounds;w.hp=level.difficulty==='Expert'?2:level.difficulty==='Hard'?3:5;w.q=makeQuestion(w.subject,rng(hash(seed)));save()},
    setAccess(key){Player.data.settings.accessibility||={};Player.data.settings.accessibility[key]=!Player.data.settings.accessibility[key];syncTheme();save()},
    exportSave(){const payload={format:'brainquest-portable-v1',created:new Date().toISOString(),player:clone(Player.data)},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`brainquest-${(Player.data.name||'hero').replace(/[^a-z0-9]+/gi,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)},
    importSave(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(data.format!=='brainquest-portable-v1'||!data.player)throw Error();if(!confirm('Replace this profile with the imported save?'))return;Player.data=data.player;Player.save();state();syncTheme();App.navigate('home');Rewards.toast('Save imported successfully!')}catch(_){Rewards.toast('This is not a valid BrainQuest save.')}};reader.readAsText(file)},
    lab(){const s=state(),houseIcon={Phoenix:'🔥',Dragon:'🐲',Owl:'🦉',Dolphin:'🐬'}[s.house]||'🏫';return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="home">← Home</button><div><p class="eyebrow">Create · explore · share offline</p><h1>♾️ Infinite Academy Lab</h1></div><span class="pill">${houseIcon} ${s.house||'Choose a House'}</span></header><section class="generator-hero card"><div><span>🌐</span><h2>Generate a New Learning World</h2><p>Theme, weather, subject, boss, branching rooms, and treasure are generated from a reusable world seed.</p><form onsubmit="event.preventDefault();InfiniteAcademy.generate(this.seed.value)"><input class="text-input" name="seed" maxlength="20" placeholder="Optional world seed"><button class="btn gold">Generate World</button></form></div></section><div class="infinite-menu"><article class="card" data-page="level-creator"><span>🛠️</span><h3>Level Builder</h3><p>Design and share challenges with offline codes.</p></article><article class="card" data-page="hero-skills"><span>🌟</span><h3>Hero Skill Tree</h3><p>${s.skillPoints} unspent skill points.</p></article><article class="card" data-page="collection-book"><span>📒</span><h3>Collections</h3><p>${s.stickers.length} stickers · ${s.cards.length} cards.</p></article><article class="card" data-page="academy-house"><span>${houseIcon}</span><h3>Academy Houses</h3><p>Reputation ${s.reputation} · Season XP ${s.seasonXp}.</p></article><article class="card" data-page="accessibility-center"><span>♿</span><h3>Accessibility</h3><p>Text, contrast, motion, and reading controls.</p></article><article class="card" data-page="save-center"><span>💾</span><h3>Save Center</h3><p>Back up or move your local hero safely.</p></article></div></div>`},
    world(){const w=state().world;if(!w)return this.lab();return `<div class="infinite-page world-${w.theme[0].toLowerCase().replace(/\W+/g,'-')}"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">Leave World</button><div><p class="eyebrow">Seed ${esc(w.seed)} · Room ${w.room}</p><h1>${w.theme[1]} ${esc(w.customName||w.theme[0])}</h1></div><span class="pill">${w.weather[1]} ${w.weather[0]}</span></header><section class="generated-world card"><div class="world-sky">${w.weather[1]}　✨　${w.weather[1]}</div><div class="world-boss">${w.boss[1]}</div><h2>${w.boss[0]}</h2><div class="world-health"><b>Hero ${'❤️'.repeat(w.hp)}</b><b>Boss ${'💜'.repeat(w.bossHp)}</b></div></section>${w.room%3===0?`<section class="branch-choice card"><h2>A fork in the road!</h2><p>Choices become part of this world's story.</p><button onclick="InfiniteAcademy.choose('treasure')">🗝️ Explore the hidden door</button><button onclick="InfiniteAcademy.choose('rest')">⛺ Rest at camp</button></section>`:`<form class="quest-question card" onsubmit="event.preventDefault();InfiniteAcademy.answer(this.answer.value)"><small>${w.subject} challenge</small><h2>${esc(w.q.text)}</h2>${w.q.options?`<div class="answer-options">${w.q.options.map(o=>`<button type="button" onclick="InfiniteAcademy.answer('${o}')">${o}</button>`).join('')}</div>`:`<div class="answer-row"><input name="answer" required autofocus><button class="btn gold">Use Hero Power</button></div>`}</form>`}<section class="path-log card"><b>Your story:</b> ${w.path.length?w.path.map(x=>x==='victory'?'⚔️':x==='practice'?'📘':x==='treasure'?'🗝️':'⛺').join(' → '):'The adventure begins…'}</section></div>`},
    creator(){const s=state(),d=s.draft;return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">← Lab</button><h1>🛠️ Challenge Builder</h1></header><form class="creator-form card" onsubmit="InfiniteAcademy.creatorPreview(event)"><label>Level name<input class="text-input" name="name" maxlength="30" required value="${esc(d?.name||'My Epic Challenge')}"></label><label>World theme<select class="text-input" name="theme">${worlds.themes.map(x=>`<option ${d?.theme===x[0]?'selected':''}>${x[0]}</option>`).join('')}</select></label><label>Learning subject<select class="text-input" name="subject">${worlds.subjects.map(x=>`<option ${d?.subject===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Difficulty<select class="text-input" name="difficulty">${['Easy','Normal','Hard','Expert'].map(x=>`<option ${d?.difficulty===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Boss rounds<input class="text-input" name="rounds" type="number" min="3" max="20" value="${d?.rounds||5}"></label><label>Treasure reward<select class="text-input" name="reward">${worlds.rewards.map(x=>`<option ${d?.reward===x[0]?'selected':''}>${x[0]}</option>`).join('')}</select></label><button class="btn gold">Build & Test</button></form>${s.shareCode?`<section class="share-code card"><h2>Offline Share Code</h2><textarea readonly>${s.shareCode}</textarea><div><button class="btn green" onclick="InfiniteAcademy.playCustom()">▶ Play Level</button><button class="btn ghost" onclick="InfiniteAcademy.copyCode()">Copy Code</button></div></section>`:''}<form class="share-code card" onsubmit="InfiniteAcademy.importLevel(event)"><h2>Import Someone's Level</h2><textarea name="code" required placeholder="Paste a challenge code"></textarea><button class="btn green">Import</button></form></div>`},
    skills(){const s=state(),skills={power:['⚔️','Power','Stronger quest rewards'],wisdom:['📘','Wisdom','More learning XP'],luck:['🍀','Luck','Rarer treasure'],heart:['❤️','Heart','More adventure health']};return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">← Lab</button><h1>🌟 Hero Skill Tree</h1><span class="pill">${s.skillPoints} points</span></header><div class="skill-tree">${Object.entries(skills).map(([id,x])=>`<article class="card"><span>${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p><div class="skill-pips">${[1,2,3,4,5].map(n=>`<i class="${n<=s.skills[id]?'on':''}"></i>`).join('')}</div><button class="btn gold" onclick="InfiniteAcademy.buySkill('${id}')" ${s.skills[id]>=5||s.skillPoints<s.skills[id]+1?'disabled':''}>Upgrade · ${s.skills[id]+1} point${s.skills[id]?'s':''}</button></article>`).join('')}</div></div>`},
    collection(){const s=state();return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">← Lab</button><h1>📒 Collection Museum</h1></header><h2>Quest Stickers</h2><div class="collection-grid">${worlds.rewards.map(x=>`<article class="card ${s.stickers.includes(x[0])?'owned':'locked'}"><span>${s.stickers.includes(x[0])?x[1]:'❔'}</span><b>${x[0]}</b></article>`).join('')}</div><h2>Boss Cards</h2><div class="collection-grid">${worlds.bosses.map(x=>`<article class="card ${s.cards.includes(x[0])?'owned':'locked'}"><span>${s.cards.includes(x[0])?x[1]:'❔'}</span><b>${x[0]}</b></article>`).join('')}</div></div>`},
    houses(){const s=state();return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">← Lab</button><h1>🏫 Academy Houses</h1></header><p class="center">Choose a team identity for seasonal adventures. All competition remains safe and local.</p><div class="house-grid">${[['Phoenix','🔥','Courage'],['Dragon','🐲','Determination'],['Owl','🦉','Wisdom'],['Dolphin','🐬','Teamwork']].map(x=>`<article class="card ${s.house===x[0]?'selected':''}"><span>${x[1]}</span><h2>${x[0]} House</h2><p>${x[2]}</p><button class="btn ${s.house===x[0]?'green':'gold'}" onclick="InfiniteAcademy.chooseHouse('${x[0]}')">${s.house===x[0]?'✓ Your House':'Join House'}</button></article>`).join('')}</div></div>`},
    access(){const a=Player.data.settings.accessibility||{};const row=(id,icon,title,text)=>`<div class="access-row"><div><b>${icon} ${title}</b><small>${text}</small></div><button class="toggle ${a[id]?'on':''}" onclick="InfiniteAcademy.setAccess('${id}')"></button></div>`;return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">← Lab</button><h1>♿ Accessibility Center</h1></header><section class="card access-list">${row('largeText','🔎','Large game text','Makes normal game text easier to read.')}${row('contrast','◐','High contrast','Strengthens colors and outlines.')}${row('calm','🧘','Calm mode','Stops decorative movement and flashing.')}${row('dyslexia','Aa','Reading-friendly font','Uses wider letter spacing and a clear font.')}</section></div>`},
    saves(){return `<div class="infinite-page"><header class="infinite-head"><button class="btn ghost" data-page="infinite-lab">← Lab</button><h1>💾 Save Center</h1></header><section class="save-panel card"><span>📤</span><div><h2>Export Hero Backup</h2><p>Download progress, wardrobe, worlds, and settings to a JSON file.</p></div><button class="btn green" onclick="InfiniteAcademy.exportSave()">Download Backup</button></section><section class="save-panel card"><span>📥</span><div><h2>Import Hero Backup</h2><p>This replaces only the currently active local profile after confirmation.</p></div><label class="btn gold">Choose Backup<input type="file" accept="application/json" hidden onchange="InfiniteAcademy.importSave(event)"></label></section></div>`}
  };
  state();Player.data.settings.accessibility||={};Player.save();syncTheme();
  const oldHome=App.home.bind(App),oldRender=App.render.bind(App);
  App.home=function infiniteHome(){return oldHome()+`<section class="infinite-banner card" data-page="infinite-lab"><span>♾️</span><div><p class="eyebrow">Worlds that never run out</p><h2>Infinite Academy Lab</h2><p>Generate adventures, build challenges, share offline codes, grow skills, and collect rare discoveries.</p></div><b>Enter Lab →</b></section>`};
  App.render=function infiniteRender(){const views={'infinite-lab':InfiniteAcademy.lab,'infinite-world':InfiniteAcademy.world,'level-creator':InfiniteAcademy.creator,'hero-skills':InfiniteAcademy.skills,'collection-book':InfiniteAcademy.collection,'academy-house':InfiniteAcademy.houses,'accessibility-center':InfiniteAcademy.access,'save-center':InfiniteAcademy.saves};if(!views[this.current])return oldRender();const screen=document.querySelector('#screen');screen.className='screen';screen.innerHTML=views[this.current]();this.bind();this.hud()};
  App.render();
})();
