// Learning center with recommendations, a focus timer, goals, and flashcards.
(() => {
  let timer=null,flash=null;
  const study=()=>Player.data.studyTools||=( {minutes:0,goal:20,active:false,seconds:600} );
  const recommendation=()=>{const d=Player.data;if((d.mathCorrect||0)<(d.fractionCorrect||0))return ['Math Training','Build confidence with quick arithmetic practice.','math'];if((d.fractionCorrect||0)<5)return ['Fraction Kingdom','Practise fractions to strengthen this skill.','fraction'];if((d.bestWpm||0)<25)return ['Typing Defense','Improve typing speed and accuracy.','typing'];return ['Memory Temple','Keep your learning balanced with a memory challenge.','memory']};
  const makeFlash=()=>{const a=2+Math.floor(Math.random()*11),b=2+Math.floor(Math.random()*11),op=Math.random()<.5?'+':'×';return{front:`${a} ${op} ${b}`,back:String(op==='+'?a+b:a*b),shown:false}};
  const render=()=>{const s=study(),[name,help,page]=recommendation(),daily=Math.min(s.goal,Math.floor(((Player.data.mathCorrect||0)+(Player.data.fractionCorrect||0)+(Player.data.wordsTyped||0)/10)/2)),percent=Math.min(100,daily/s.goal*100);flash||=makeFlash();return `<div class="learning-tools"><header class="page-head"><div><p class="eyebrow">Learn your way</p><h1>📚 Learning Tools</h1></div><button class="btn ghost" data-page="profile">← Profile</button></header><section class="learning-recommendation card"><span>💡</span><div><p class="eyebrow">Recommended next step</p><h2>${name}</h2><p>${help}</p></div><button class="btn gold" data-page="${page}">Practise now</button></section><div class="learning-tool-grid"><section class="card focus-tool"><span>⏱️</span><h2>Focus Timer</h2><strong id="study-time">${Math.floor(s.seconds/60)}:${String(s.seconds%60).padStart(2,'0')}</strong><p>Focused learning: ${s.minutes} minute${s.minutes===1?'':'s'}</p><button class="btn ${s.active?'red':'green'}" onclick="LearningTools.toggleTimer()">${s.active?'Pause':'Start 10 Minutes'}</button></section><section class="card goal-tool"><span>🎯</span><h2>Daily Learning Goal</h2><strong>${daily} / ${s.goal}</strong><div class="bar" style="--value:${percent}%"><i></i></div><p>${daily>=s.goal?'Goal complete — amazing work!':'Keep practising to reach today’s goal.'}</p><button class="btn ghost" onclick="LearningTools.setGoal()">Set goal</button></section></div><section class="flashcard-tool card"><div><p class="eyebrow">Math Flashcard</p><h2>${flash.shown?`${flash.front} = ${flash.back}`:flash.front}</h2><p>${flash.shown?'Great! Try the next one.':'Solve it in your head, then reveal the answer.'}</p></div><div class="actions"><button class="btn ghost" onclick="LearningTools.reveal()">Reveal answer</button><button class="btn gold" onclick="LearningTools.nextCard()">Next card</button></div></section></div>`};
  const updateTimer=()=>{const s=study(),display=document.querySelector('#study-time');if(display)display.textContent=`${Math.floor(s.seconds/60)}:${String(s.seconds%60).padStart(2,'0')}`};
  window.LearningTools={toggleTimer(){const s=study();if(s.active){s.active=false;clearInterval(timer);timer=null;Player.save();App.render();return}s.active=true;timer=setInterval(()=>{if(!s.active)return;if(--s.seconds<=0){s.minutes+=10;s.seconds=600;s.active=false;clearInterval(timer);timer=null;Player.addRewards(80,25,0,1);Rewards.toast('Focus session complete! Great work!');App.render()}else updateTimer()},1000);App.render()},setGoal(){const current=study(),next=prompt('Set your daily learning goal (5–60):',current.goal);const goal=Math.max(5,Math.min(60,Number(next)));if(Number.isFinite(goal)){current.goal=goal;Player.save();App.render()}},reveal(){flash.shown=true;App.render()},nextCard(){flash=makeFlash();App.render()},render};
  const oldProfile=App.profile.bind(App),oldRender=App.render.bind(App),oldNavigate=App.navigate.bind(App);
  App.profile=function toolsProfile(){return oldProfile()+`<article class="learning-tools-banner card" data-page="learning-tools"><span>📚</span><div><h3>Learning Tools</h3><p>Focus timer, flashcards, goals, and personalised practice.</p></div><b>Open →</b></article>`};
  App.navigate=function toolsNavigate(page){if(page!=='learning-tools'){clearInterval(timer);timer=null;study().active=false}if(page==='learning-tools'){this.current=page;return App.render()}return oldNavigate(page)};
  App.render=function toolsRender(){if(this.current==='learning-tools'){const screen=document.querySelector('#screen');screen.className='screen';screen.innerHTML=render();this.bind();this.hud();return}return oldRender()};
})();
