// Safe local multiplayer: two to four players share one device in a math relay.
(() => {
  let game=null;
  const question=()=>{const a=3+Math.floor(Math.random()*17),b=2+Math.floor(Math.random()*12),op=Math.random()<.5?'+':'×';return{text:`${a} ${op} ${b} = ?`,answer:String(op==='+'?a+b:a*b)}};
  const playerName=index=>`Player ${index+1}`;
  const start=players=>{game={players,turn:0,round:1,scores:Array(players).fill(0),q:question(),finished:false};App.current='multiplayer-arena';App.render()};
  const answer=value=>{if(!game||game.finished)return;if(String(value).trim()===game.q.answer)game.scores[game.turn]++;game.turn++;if(game.turn===game.players){game.turn=0;game.round++}if(game.round>3){game.finished=true;const highest=Math.max(...game.scores),winners=game.scores.map((score,index)=>score===highest?playerName(index):null).filter(Boolean);Player.addRewards(60,30,0,1);Player.data.gamesPlayed++;Player.save()}else game.q=question();App.render()};
  const render=()=>{if(!game)return `<section class="multiplayer-setup card"><h1>👥 Local Multiplayer Arena</h1><p>Choose how many players will take turns on this device.</p><div class="player-counts">${[2,3,4].map(number=>`<button class="btn gold" onclick="MultiplayerArena.start(${number})">${number} Players</button>`).join('')}</div></section>`;if(game.finished){const high=Math.max(...game.scores),winners=game.scores.map((score,index)=>score===high?playerName(index):null).filter(Boolean);return `<section class="multiplayer-setup card"><span class="arena-trophy">🏆</span><h1>${winners.join(' & ')} win${winners.length>1?'':'s'}!</h1><div class="arena-scores">${game.scores.map((score,index)=>`<b>${playerName(index)} <span>${score}</span></b>`).join('')}</div><button class="btn gold" onclick="MultiplayerArena.reset()">New Match</button></section>`}return `<section class="multiplayer-game card"><header><button class="btn ghost" data-page="games">← Games</button><div><p class="eyebrow">Round ${game.round} / 3</p><h1>👥 Math Relay</h1></div><span class="pill">${game.players} players</span></header><div class="arena-scores">${game.scores.map((score,index)=>`<b class="${index===game.turn?'active':''}">${playerName(index)} <span>${score}</span></b>`).join('')}</div><div class="relay-question"><p>Pass the device to <strong>${playerName(game.turn)}</strong></p><h2>${game.q.text}</h2><form class="answer-row" onsubmit="event.preventDefault();MultiplayerArena.answer(this.elements.answer.value)"><input name="answer" inputmode="numeric" autofocus required><button class="btn gold">Lock Answer</button></form></div></section>`};
  window.MultiplayerArena={start,answer,reset(){game=null;App.render()},render};
  const oldCards=App.gameCards.bind(App),oldRender=App.render.bind(App),oldNavigate=App.navigate.bind(App);
  App.gameCards=function multiplayerCard(){return oldCards()+`<div class="section-title"><div><p class="eyebrow">Same device · play together</p><h2>Multiplayer</h2></div></div><article class="game-card card multiplayer-card" data-page="multiplayer-arena"><div class="emoji">👥</div><h3>Local Multiplayer Arena</h3><p>Challenge 2–4 players in a turn-based math relay.</p><span class="go">→</span></article>`};
  App.navigate=function multiplayerNavigate(page){if(page==='multiplayer-arena'){game=null;this.current=page;return App.render()}return oldNavigate(page)};
  App.render=function multiplayerRender(){if(this.current==='multiplayer-arena'){const screen=document.querySelector('#screen');screen.className='screen';screen.innerHTML=render();this.bind();this.hud();return}return oldRender()};
})();
