// Three additional learning games: timed arithmetic, geometry, and sequences.
(() => {
  const random=list=>list[Math.floor(Math.random()*list.length)];
  const save=()=>Player.save();
  const reward=(xp,coins)=>{Player.addRewards(xp,coins,0,1);Player.data.gamesPlayed++;save()};
  const mathQuestion=()=>{const a=2+Math.floor(Math.random()*18),b=2+Math.floor(Math.random()*18),op=random(['+','−','×']);const answer=op==='+'?a+b:op==='−'?Math.max(a,b)-Math.min(a,b):a*b;return{text:op==='−'?`${Math.max(a,b)} − ${Math.min(a,b)} = ?`:`${a} ${op} ${b} = ?`,answer:String(answer)}};
  const geometry=[['How many sides does a triangle have?','3',['2','3','4','5']],['How many sides does a square have?','4',['3','4','5','6']],['Which shape has no corners?','Circle',['Circle','Triangle','Square','Rectangle']],['How many right angles does a rectangle have?','4',['1','2','3','4']],['Which shape has 5 sides?','Pentagon',['Hexagon','Pentagon','Triangle','Circle']]];
  const sequence=()=>{const start=2+Math.floor(Math.random()*8),step=2+Math.floor(Math.random()*7),values=[start,start+step,start+step*2,start+step*3],answer=start+step*4,options=[answer,answer+step,answer-step,answer+2].sort(()=>Math.random()-.5);return{text:`${values.join(', ')}, ?`,answer:String(answer),options:options.map(String)}};
  const states={rapid:null,geometry:null,detective:null};
  const result=(title,score,total)=>`<section class="new-game-result card"><span>🏆</span><h2>${title}</h2><p>You scored <b>${score}</b>${total?` out of ${total}`:''}.</p><button class="btn gold" data-page="games">Back to Games</button></section>`;
  const Rapid={start(){clearInterval(states.rapid?.timer);states.rapid={score:0,time:45,q:mathQuestion(),done:false,timer:null};states.rapid.timer=setInterval(()=>{const s=states.rapid;if(!s||s.done)return;--s.time;if(s.time<=0){s.done=true;clearInterval(s.timer);reward(s.score*12,Math.max(10,s.score*4));App.render()}else{const timer=document.querySelector('#rapid-timer');if(timer)timer.textContent=s.time}},1000);App.current='rapid-fire';App.render()},answer(value){const s=states.rapid;if(!s||s.done)return;if(String(value).trim()===s.q.answer){s.score++;s.q=mathQuestion();document.querySelector('#rapid-answer').value='';App.render()}},render(){const s=states.rapid;if(!s)return '';if(s.done)return result('Rapid Fire Complete!',s.score);return `<section class="new-game card"><header><button class="btn ghost" data-page="games">← Games</button><div><p class="eyebrow">Beat the clock</p><h1>⚡ Rapid Fire Math</h1></div><b class="new-timer">⏱ <span id="rapid-timer">${s.time}</span>s</b></header><div class="new-score">Score: ${s.score}</div><h2>${s.q.text}</h2><form class="answer-row" onsubmit="event.preventDefault();RapidFire.answer(this.elements.answer.value)"><input id="rapid-answer" name="answer" inputmode="numeric" autofocus required><button class="btn gold">Answer</button></form></section>`}};
  const Quiz=(id,title,icon,questions)=>({start(){states[id]={round:0,score:0,q:typeof questions==='function'?questions():random(questions),done:false};App.current=id;App.render()},answer(value){const s=states[id];if(!s||s.done)return;if(value===s.q.answer)s.score++;s.round++;if(s.round>=5){s.done=true;reward(s.score*30,s.score*15)}else s.q=typeof questions==='function'?questions():random(questions);App.render()},render(){const s=states[id];if(!s)return '';if(s.done)return result(`${title} Complete!`,s.score,5);return `<section class="new-game card"><header><button class="btn ghost" data-page="games">← Games</button><div><p class="eyebrow">Round ${s.round+1} / 5</p><h1>${icon} ${title}</h1></div><b class="new-score">${s.score} points</b></header><h2>${s.q.text}</h2><div class="new-options">${s.q.options.map(option=>`<button onclick="${id==='geometry'?'GeometryQuest':'NumberDetective'}.answer('${option}')">${option}</button>`).join('')}</div></section>`}});
  const Geometry=Quiz('geometry','Geometry Quest','📐',geometry),Detective=Quiz('detective','Number Detective','🔎',sequence);
  window.RapidFire=Rapid;window.GeometryQuest=Geometry;window.NumberDetective=Detective;
  const oldCards=App.gameCards.bind(App),oldRender=App.render.bind(App),oldNavigate=App.navigate.bind(App);
  App.gameCards=function newGameCards(){return oldCards()+`<div class="section-title"><div><p class="eyebrow">New challenges</p><h2>Skill Builders</h2></div></div><div class="game-grid"><article class="game-card card rapid-card" data-page="rapid-fire"><div class="emoji">⚡</div><h3>Rapid Fire Math</h3><p>Solve as many questions as you can before time runs out.</p><span class="go">→</span></article><article class="game-card card geometry-card" data-page="geometry"><div class="emoji">📐</div><h3>Geometry Quest</h3><p>Explore shapes, sides, corners, and angles.</p><span class="go">→</span></article><article class="game-card card detective-card" data-page="detective"><div class="emoji">🔎</div><h3>Number Detective</h3><p>Find the missing number in each sequence.</p><span class="go">→</span></article></div>`};
  App.navigate=function newGamesNavigate(page){if(page!=='rapid-fire')clearInterval(states.rapid?.timer);if(page==='rapid-fire')return Rapid.start();if(page==='geometry')return Geometry.start();if(page==='detective')return Detective.start();return oldNavigate(page)};
  App.render=function newGamesRender(){const view={"rapid-fire":Rapid,geometry:Geometry,detective:Detective}[this.current];if(view){const screen=document.querySelector('#screen');screen.className='screen';screen.innerHTML=view.render();this.bind();this.hud();return}return oldRender()};
})();
