// Coin-powered clothing customization. Pets remain available.
(() => {
  const items=[
    ['Sky T-Shirt','shirt','👕',180,'#42a5f5'],['Dragon T-Shirt','shirt','👕',300,'#ef5350'],['Forest Hoodie','shirt','🧥',420,'#43a047'],['Galaxy Jacket','shirt','🧥',650,'#673ab7'],
    ['Adventure Shorts','pants','🩳',160,'#ffb74d'],['Ocean Shorts','pants','🩳',260,'#1976d2'],['Knight Pants','pants','👖',380,'#455a64'],['Rainbow Pants','pants','👖',520,'#ab47bc'],
    ['Hero Cap','hat','🧢',190,'#ef5350'],['Wizard Hat','hat','🧙',420,'#5e35b1'],['Royal Crown','hat','👑',700,'#ffd54f'],
    ['Red Sneakers','shoes','👟',170,'#e53935'],['Star Boots','shoes','🥾',350,'#fbc02d'],['Shadow Shoes','shoes','👟',480,'#263238']
  ];
  const pets=[['Dog','🐶',250],['Cat','🐱',250],['Baby Dragon','🐉',900],['Mini Robot','🤖',700],['Fox','🦊',500],['Owl','🦉',450]];
  pets.push(['Penguin','🐧',500],['Unicorn','🦄',800],['Panda','🐼',600],['Phoenix','🔥',950]);
  const words={en:{title:'Hero Wardrobe',sub:'Buy clothes with coins and create your hero',shirt:'Shirts',pants:'Shorts & Pants',hat:'Hats',shoes:'Shoes',pets:'Pets',wear:'Wear',wearing:'✓ Wearing',buy:'Buy',home:'Home',poor:'Earn more coins by learning!'},fr:{title:'Garde-robe du héros',sub:'Achète des vêtements avec des pièces et crée ton héros',shirt:'Hauts',pants:'Shorts et pantalons',hat:'Chapeaux',shoes:'Chaussures',pets:'Compagnons',wear:'Porter',wearing:'✓ Porté',buy:'Acheter',home:'Accueil',poor:'Gagne plus de pièces en apprenant !'},ar:{title:'خزانة البطل',sub:'اشترِ الملابس بالعملات وصمّم بطلك',shirt:'القمصان',pants:'السراويل',hat:'القبعات',shoes:'الأحذية',pets:'الحيوانات الأليفة',wear:'ارتداء',wearing:'✓ مُرتدى',buy:'شراء',home:'الرئيسية',poor:'اربح المزيد من العملات بالتعلّم!'}};
  const L=()=>Player.data.settings.language||'en',T=()=>words[L()]||words.en,find=n=>items.find(x=>x[0]===n);
  const ensure=()=>{Player.data.outfit||={shirt:'Sky T-Shirt',pants:'Adventure Shorts',hat:'',shoes:'Red Sneakers'};['Sky T-Shirt','Adventure Shorts','Red Sneakers'].forEach(n=>{if(!Player.data.inventory.includes(n))Player.data.inventory.push(n)})};ensure();Player.save();
  window.Wardrobe={figure(size=''){const o=Player.data.outfit,s=find(o.shirt),p=find(o.pants),h=find(o.hat),f=find(o.shoes);return `<div class="wearable-hero ${size}" style="--shirt:${s?.[4]||'#42a5f5'};--pants:${p?.[4]||'#ffb74d'};--shoes:${f?.[4]||'#e53935'}"><i>${h?.[2]||''}</i><b>🙂</b><em>${s?.[2]||'👕'}</em><strong>${p?.[2]||'🩳'}</strong><small>${f?.[2]||'👟'}</small></div>`},buy(n){const x=find(n);if(Player.data.coins<x[3])return Rewards.toast(T().poor);Player.data.coins-=x[3];Player.data.inventory.push(n);Player.save();App.render()},equip(n){const x=find(n);Player.data.outfit[x[1]]=n;Player.save();App.render()},pet(n,i,c){if(!Player.data.inventory.includes(n)){if(Player.data.coins<c)return Rewards.toast(T().poor);Player.data.coins-=c;Player.data.inventory.push(n)}Player.data.petName=n;Player.data.pet=i;Player.save();App.render()},render(){ensure();const t=T(),group=slot=>`<section class="wardrobe-section"><h2>${t[slot]}</h2><div class="wardrobe-grid">${items.filter(x=>x[1]===slot).map(x=>{const owned=Player.data.inventory.includes(x[0]),on=Player.data.outfit[slot]===x[0];return `<article class="wardrobe-item card ${on?'wearing':''}"><span>${x[2]}</span><h3>${x[0]}</h3><p>🪙 ${x[3]}</p><button class="btn ${on||owned?'green':'gold'}" ${on?'disabled':`onclick="Wardrobe.${owned?'equip':'buy'}('${x[0]}')"`}>${on?t.wearing:owned?t.wear:t.buy}</button></article>`}).join('')}</div></section>`;return `<div class="page-head"><div><p class="eyebrow">${t.sub}</p><h1>👕 ${t.title}</h1></div><button class="btn ghost" data-page="home">${t.home}</button></div><div class="wardrobe-preview card">${this.figure('large')}<h2>${Player.data.name}<br>🪙 ${Player.data.coins}</h2></div>${['shirt','pants','hat','shoes'].map(group).join('')}<section class="wardrobe-section"><h2>🐾 ${t.pets}</h2><div class="wardrobe-grid">${pets.map(x=>`<article class="wardrobe-item card"><span>${x[1]}</span><h3>${x[0]}</h3><p>🪙 ${x[2]}</p><button class="btn gold" onclick="Wardrobe.pet('${x[0]}','${x[1]}',${x[2]})">${Player.data.inventory.includes(x[0])?t.wear:t.buy}</button></article>`).join('')}</div></section>`},apply(){document.querySelectorAll('.avatar').forEach(e=>e.innerHTML=this.figure('small'));document.querySelectorAll('.player-fighter .sprite').forEach(e=>e.innerHTML=this.figure('battle'));const r=document.querySelector('.room-frame span');if(r)r.outerHTML=this.figure('room')}};
  App.shop=()=>{const t=T();return `<div class="page-head"><div><p class="eyebrow">${t.sub}</p><h1>🐾 ${t.pets}</h1></div><button class="btn ghost" data-page="home">${t.home}</button></div><section class="wardrobe-section"><div class="wardrobe-grid">${pets.map(x=>`<article class="wardrobe-item card"><span>${x[1]}</span><h3>${x[0]}</h3><p>🪙 ${x[2]}</p><button class="btn ${Player.data.inventory.includes(x[0])?'green':'gold'}" onclick="Wardrobe.pet('${x[0]}','${x[1]}',${x[2]})">${Player.data.inventory.includes(x[0])?t.wear:t.buy}</button></article>`).join('')}</div></section>`};
  const old=App.render.bind(App);App.render=function(){if(this.current==='wardrobe'){document.querySelector('#screen').innerHTML=Wardrobe.render();this.bind();this.hud()}else old();Wardrobe.apply()};
  const oldGame=App.renderGame.bind(App);App.renderGame=function(g){oldGame(g);Wardrobe.apply()};
})();
