// Book-style hero customizer with localized wearable categories.
(() => {
  const catalog=[
    ['body','Boy Hero','👦',0,'#f2b38f'],['body','Girl Hero','👧',0,'#f2b38f'],['body','Warm Body','🧍',0,'#f2b38f'],['body','Golden Body','🧍',180,'#c98656'],['face','Happy Face','😊',0],['face','Brave Face','😎',220],
    ['boyHair','Hero Hair','🧑',180],['boyHair','Spiky Hair','👨‍🎤',300],['girlHair','Explorer Hair','👧',180],['girlHair','Royal Hair','👸',350],
    ['mask','Ninja Mask','🥷',300],['mask','Robot Mask','🤖',450],['shoes','Red Sneakers','👟',170,'#e53935'],['shoes','Star Boots','🥾',350,'#fbc02d'],
    ['gloves','Power Gloves','🧤',240],['gloves','Ice Gloves','🧤',360],['emblem','Star Emblem','⭐',200],['emblem','Dragon Emblem','🐲',400],
    ['belt','Adventure Belt','➖',180],['belt','Champion Belt','🏆',450],['costume','Sky T-Shirt','👕',180,'#42a5f5'],['costume','Forest Hoodie','🧥',420,'#43a047'],['costume','Galaxy Jacket','🧥',650,'#673ab7'],
    ['pants','Adventure Shorts','🩳',160,'#ffb74d'],['pants','Knight Pants','👖',380,'#455a64'],['cape','Shadow Cape','🦸',420,'#202030'],['cape','Royal Cape','🦸',600,'#b71c1c']
  ];
  const pets=[['Dog','🐶',250],['Cat','🐱',250],['Baby Dragon','🐉',900],['Mini Robot','🤖',700],['Fox','🦊',500],['Owl','🦉',450]];
  const extraCatalog={
    body:[['Bronze Body','🧍',220,'#ad7145'],['Cocoa Body','🧍',240,'#825033'],['Moon Body','🧍',280,'#ead1bd'],['Sunset Body','🧍',320,'#d99a72'],['Ocean Body','🧍',380,'#75b9c7'],['Alien Body','👽',500,'#75c96b']],
    face:[['Wink Face','😉',120],['Cool Face','😎',180],['Laughing Face','😄',240],['Determined Face','😤',300],['Star Face','🤩',360],['Silly Face','😜',420],['Thinking Face','🤔',480],['Robot Face','🤖',560]],
    boyHair:[['Curly Hair','👨‍🦱',220],['Blond Hair','👱‍♂️',250],['Red Hair','👨‍🦰',280],['Mohawk Hair','🧑‍🎤',340],['Surfer Hair','🤙',380],['Ninja Hair','🥷',420],['Wizard Hair','🧙‍♂️',500],['Prince Hair','🤴',600]],
    girlHair:[['Curly Girl Hair','👩‍🦱',220],['Blond Girl Hair','👱‍♀️',250],['Red Girl Hair','👩‍🦰',280],['Ponytail Hair','👧',340],['Pop Star Hair','👩‍🎤',380],['Ninja Girl Hair','🥷',420],['Wizard Girl Hair','🧙‍♀️',500],['Princess Hair','👸',600]],
    mask:[['Hero Mask','🥸',180],['Mystery Mask','🎭',240],['Space Mask','👨‍🚀',320],['Monster Mask','👹',380],['Ghost Mask','👻',420],['Dragon Mask','🐲',480],['Knight Mask','🪖',540],['Alien Mask','👽',620]],
    shoes:[['Blue Trainers','👟',200,'#1976d2'],['Green Runners','👟',240,'#43a047'],['Golden Shoes','👞',300,'#f9a825'],['Knight Boots','🥾',360,'#795548'],['Snow Boots','🥾',420,'#90caf9'],['Rocket Shoes','🚀',500,'#ef6c00'],['Shadow Shoes','👞',560,'#263238'],['Royal Shoes','👞',650,'#7b1fa2']],
    gloves:[['Fire Gloves','🧤',280],['Nature Gloves','🧤',320],['Golden Gloves','🥊',400],['Ninja Gloves','🥷',440],['Robot Gloves','🤖',500],['Dragon Gloves','🐉',560],['Space Gloves','👨‍🚀',620],['Royal Gloves','🧤',700]],
    emblem:[['Lightning Emblem','⚡',240],['Moon Emblem','🌙',280],['Heart Emblem','❤️',320],['Shield Emblem','🛡️',360],['Fire Emblem','🔥',420],['Crown Emblem','👑',480],['Rocket Emblem','🚀',540],['Gem Emblem','💎',650]],
    belt:[['Utility Belt','🧰',220],['Ninja Belt','🥋',260],['Golden Belt','🟨',320],['Space Belt','🪐',380],['Pirate Belt','🏴‍☠️',420],['Dragon Belt','🐉',480],['Magic Belt','✨',540],['Royal Belt','👑',620]],
    costume:[['Hero Suit','🦸',240,'#d32f2f'],['Ninja Suit','🥷',300,'#263238'],['Knight Armor','🛡️',380,'#78909c'],['Explorer Shirt','👕',440,'#ef6c00'],['Space Suit','👨‍🚀',520,'#eceff1'],['Dragon Armor','🐉',600,'#2e7d32'],['Wizard Robe','🧙',680,'#512da8']],
    pants:[['Blue Jeans','👖',200,'#1565c0'],['Sport Shorts','🩳',240,'#e53935'],['Explorer Pants','👖',300,'#6d4c41'],['Ninja Pants','🥷',360,'#212121'],['Snow Pants','👖',420,'#90caf9'],['Space Pants','👨‍🚀',480,'#eceff1'],['Dragon Pants','🐉',540,'#2e7d32'],['Royal Pants','👖',620,'#6a1b9a']],
    cape:[['Hero Cape','🦸',250,'#e53935'],['Ocean Cape','🌊',300,'#1976d2'],['Forest Cape','🍃',350,'#388e3c'],['Golden Cape','✨',400,'#f9a825'],['Fire Cape','🔥',480,'#ef6c00'],['Ice Cape','❄️',520,'#80deea'],['Dragon Cape','🐉',680,'#2e7d32'],['Galaxy Cape','🌌',760,'#4527a0']]
  };
  Object.entries(extraCatalog).forEach(([category,items])=>items.forEach(item=>catalog.push([category,...item])));
  catalog.filter(item=>item[0]==='costume').forEach(item=>item[5]='boy');
  [
    ['Academy Uniform','🎨',180,'#3949ab'],['Sports Star','🎨',240,'#ec407a'],['Super Girl Suit','🎨',300,'#d81b60'],['Moon Knight Armor','🎨',380,'#7986cb'],['Forest Ranger','🎨',440,'#43a047'],
    ['Crystal Princess','🎨',520,'#7e57c2'],['Galaxy Explorer','🎨',580,'#5c6bc0'],['Dragon Rider','🎨',640,'#00897b'],['Magic Academy','🎨',700,'#8e24aa'],['Phoenix Guardian','🎨',780,'#f4511e']
  ].forEach(item=>catalog.push(['costume',...item,'girl']));
  const customizationExtras={
    hat:[['Hero Cap','🧢',120],['Royal Crown','👑',240],['Wizard Hat','🪄',300],['Knight Helmet','⛑️',340],['Pirate Hat','🏴‍☠️',380],['Space Helmet','🚀',420],['Flower Crown','🌸',460],['Ninja Hood','🥷',500],['Dragon Crown','🐉',560],['Galaxy Crown','✨',650]],
    glasses:[['Round Glasses','◉',100],['Cool Shades','▰',160],['Star Glasses','★',220],['Science Goggles','⚗️',260],['Hero Visor','⚡',300],['Heart Glasses','♥',340],['Space Visor','🚀',400],['Magic Glasses','✨',440],['Royal Monocle','◐',500],['Galaxy Shades','🌌',580]],
    wings:[['Angel Wings','🪽',240],['Butterfly Wings','🦋',280],['Dragon Wings','🐉',340],['Fairy Wings','✨',380],['Fire Wings','🔥',440],['Ice Wings','❄️',480],['Robot Wings','⚙️',540],['Shadow Wings','🌑',600],['Rainbow Wings','🌈',680],['Galaxy Wings','🌌',760]],
    weapon:[['Magic Wand','🪄',180],['Hero Shield','🛡️',220],['Knight Sword','⚔️',280],['Explorer Compass','🧭',320],['Builder Hammer','🔨',360],['Ninja Staff','🥋',400],['Space Blaster','🚀',460],['Crystal Staff','💎',520],['Dragon Sword','🐉',620],['Phoenix Scepter','🔥',720]],
    backpack:[['School Backpack','🎒',140],['Explorer Pack','🧭',200],['Sports Bag','🏅',240],['Magic Satchel','✨',300],['Knight Pack','🛡️',340],['Jet Pack','🚀',420],['Dragon Pack','🐉',480],['Crystal Pack','💎',540],['Royal Pack','👑',600],['Galaxy Pack','🌌',680]],
    necklace:[['Friendship Necklace','♡',100],['Star Necklace','★',160],['Moon Necklace','☾',200],['Hero Medal','🏅',240],['Crystal Necklace','◆',300],['Dragon Pendant','🐉',360],['Magic Amulet','✨',420],['Royal Necklace','👑',480],['Phoenix Pendant','🔥',560],['Galaxy Necklace','🌌',640]],
    aura:[['Sparkle Aura','✨',200],['Fire Aura','🔥',260],['Ice Aura','❄️',300],['Nature Aura','🍃',340],['Lightning Aura','⚡',380],['Magic Aura','🔮',440],['Shadow Aura','🌑',500],['Rainbow Aura','🌈',560],['Phoenix Aura','🔥',640],['Galaxy Aura','🌌',720]],
    background:[['Bedroom','🛏️',0],['Castle','🏰',180],['Spaceship','🚀',220],['Forest','🌲',240],['Beach','🏖️',280],['Hero City','🏙️',320],['Classroom','🏫',360],['Ninja Dojo','🥋',420],['Underwater','🌊',500],['Volcano','🌋',580]],
    pose:[['Ready Pose','●',0],['Champion Pose','🏆',120],['Hero Pose','⚡',160],['Power Pose','💪',200],['Magic Pose','✨',240],['Ninja Pose','🥷',280],['Flying Pose','🪽',320],['Victory Pose','✌️',360],['Royal Pose','👑',420],['Dance Pose','♫',480]]
  };
  Object.entries(customizationExtras).forEach(([category,items])=>items.forEach(item=>catalog.push([category,...item])));
  pets.push(['Penguin','🐧',500],['Unicorn','🦄',800],['Panda','🐼',600],['Phoenix','🔥',950]);
  const tx={
    en:{title:'Customization',hero:'My Hero',body:'Body',face:'Face',boyHair:'Boy Hair',girlHair:'Girl Hair',mask:'Mask',shoes:'Shoes',gloves:'Gloves',emblem:'Emblems',belt:'Belt',costume:'Outfit',pants:'Shorts & Pants',cape:'Cape',pets:'Pets',buy:'Buy',wear:'Wear',on:'Wearing',back:'Home',coins:'Coins',xp:'XP'},
    fr:{title:'Personnalisation',hero:'Mon héros',body:'Corps',face:'Visage',boyHair:'Cheveux garçon',girlHair:'Cheveux fille',mask:'Masque',shoes:'Chaussures',gloves:'Gants',emblem:'Emblèmes',belt:'Ceinture',costume:'Costume',pants:'Shorts et pantalons',cape:'Cape',pets:'Compagnons',buy:'Acheter',wear:'Porter',on:'Porté',back:'Accueil',coins:'Pièces',xp:'XP'},
    ar:{title:'تخصيص البطل',hero:'بطلي',body:'الجسم',face:'الوجه',boyHair:'شعر الأولاد',girlHair:'شعر البنات',mask:'القناع',shoes:'الأحذية',gloves:'القفازات',emblem:'الشعارات',belt:'الحزام',costume:'الزي',pants:'السراويل',cape:'العباءة',pets:'الحيوانات الأليفة',buy:'شراء',wear:'ارتداء',on:'مُرتدى',back:'الرئيسية',coins:'العملات',xp:'الخبرة'}
  };
  const language=()=>Player.data.settings.language||'en',T=()=>tx[language()]||tx.en;
  const ensure=()=>{Player.data.outfit||={};Player.data.outfit.body||='Warm Body';Player.data.outfit.face||='Happy Face';Player.data.wardrobeCategory||='costume';['Warm Body','Happy Face'].forEach(n=>{if(!Player.data.inventory.includes(n))Player.data.inventory.push(n)})};ensure();Player.save();
  const find=n=>catalog.find(x=>x[1]===n);
  const oldBuy=Wardrobe.buy.bind(Wardrobe),oldEquip=Wardrobe.equip.bind(Wardrobe);
  Wardrobe.buy=function(n){const x=find(n);if(!x)return oldBuy(n);if(Player.data.coins<x[3])return Rewards.toast(T().coins+' ❌');Player.data.coins-=x[3];Player.data.inventory.push(n);Wardrobe.heroAnimation='celebrate';Player.save();App.render()};
  Wardrobe.equip=function(n){const x=find(n);if(!x)return oldEquip(n);Player.data.outfit[x[0]]=n;if(x[0]==='background')heroView().background=n.toLowerCase().replace(/[^a-z0-9]+/g,'-');Wardrobe.heroAnimation='changing';Player.save();App.render()};
  Wardrobe.category=function(c){const menu=document.querySelector('.book-categories'),menuScroll=menu?.scrollTop||0,pageScroll=window.scrollY;Player.data.wardrobeCategory=c;Player.save();App.render();requestAnimationFrame(()=>{const nextMenu=document.querySelector('.book-categories');if(nextMenu)nextMenu.scrollTop=menuScroll;window.scrollTo(0,pageScroll)})};
  const heroView=()=>Player.data.heroView||={background:'bedroom',rotation:0,zoom:1};
  Wardrobe.heroBackground=function(background){heroView().background=background;Player.save();App.render()};
  Wardrobe.rotateHero=function(direction){const view=heroView();view.rotation+=direction*18;if(view.rotation>36)view.rotation=-36;if(view.rotation< -36)view.rotation=36;Player.save();App.render()};
  Wardrobe.zoomHero=function(direction){const view=heroView();view.zoom=Math.max(.75,Math.min(1.25,Math.round((view.zoom+direction*.1)*10)/10));Player.save();App.render()};
  Wardrobe.stage=function(figure){const view=heroView(),backgrounds=[['bedroom','🛏️'],['castle','🏰'],['spaceship','🚀'],['forest','🌲']];return `<div class="hero-stage scene-${view.background}"><div class="stage-light"></div><div class="hero-model" style="--hero-turn:${view.rotation}deg;--hero-zoom:${view.zoom}">${figure}</div><div class="hero-shadow"></div><div class="hero-platform"></div></div><div class="stage-controls"><div class="scene-buttons">${backgrounds.map(([name,icon])=>`<button class="${view.background===name?'active':''}" onclick="Wardrobe.heroBackground('${name}')" title="${name}">${icon}</button>`).join('')}</div><div class="view-buttons"><button onclick="Wardrobe.rotateHero(-1)" title="Rotate left">↶</button><button onclick="Wardrobe.rotateHero(1)" title="Rotate right">↷</button><button onclick="Wardrobe.zoomHero(-1)" title="Zoom out">−</button><button onclick="Wardrobe.zoomHero(1)" title="Zoom in">＋</button></div></div>`};
  Wardrobe.setFilter=function(filter){Player.data.wardrobeFilter=filter;Player.save();App.render()};
  Wardrobe.removeItem=function(category){if(category==='pets'){Player.data.pet='';Player.data.petName=''}else if(category==='body')Player.data.outfit.body='Boy Hero';else if(category==='background'){Player.data.outfit.background='';heroView().background='bedroom'}else if(category==='pose')Player.data.outfit.pose='Ready Pose';else Player.data.outfit[category]='';Wardrobe.heroAnimation='changing';Player.save();App.render()};
  Wardrobe.randomize=function(){const outfit=Player.data.outfit,pick=items=>items[Math.floor(Math.random()*items.length)],ownedBodies=catalog.filter(item=>item[0]==='body'&&Player.data.inventory.includes(item[1]));if(ownedBodies.length)outfit.body=pick(ownedBodies)[1];const isGirl=outfit.body==='Girl Hero',categories=['face',isGirl?'girlHair':'boyHair','mask','hat','glasses','shoes','gloves','emblem','necklace','belt','costume','pants','cape','wings','weapon','backpack','aura','background','pose'];categories.forEach(category=>{const owned=catalog.filter(item=>item[0]===category&&Player.data.inventory.includes(item[1])&&(category!=='costume'||item[5]===(isGirl?'girl':'boy')));if(owned.length)outfit[category]=pick(owned)[1]});const ownedPets=pets.filter(item=>Player.data.inventory.includes(item[0]));if(ownedPets.length){const pet=pick(ownedPets);Player.data.petName=pet[0];Player.data.pet=pet[1]}if(outfit.background)heroView().background=outfit.background.toLowerCase().replace(/[^a-z0-9]+/g,'-');Wardrobe.heroAnimation='celebrate';Player.save();App.render()};
  Wardrobe.removeAll=function(){const outfit=Player.data.outfit;['boyHair','girlHair','mask','hat','glasses','shoes','gloves','emblem','necklace','belt','costume','shirt','pants','cape','wings','weapon','backpack','aura'].forEach(category=>outfit[category]='');outfit.face='Happy Face';outfit.background='';outfit.pose='Ready Pose';Player.data.pet='';Player.data.petName='';heroView().background='bedroom';heroView().rotation=0;heroView().zoom=1;Wardrobe.heroAnimation='changing';Player.save();App.render()};
  Wardrobe.figure=function(size=''){ensure();const o=Player.data.outfit,get=slot=>find(o[slot]),body=get('body'),face=get('face'),hair=get('boyHair')||get('girlHair'),mask=get('mask'),costume=get('costume'),pants=get('pants'),cape=get('cape'),gloves=get('gloves'),emblem=get('emblem'),belt=get('belt'),shoes=get('shoes');return `<div class="book-hero ${size}" style="--skin:${body?.[4]||'#f2b38f'};--shirt:${costume?.[4]||'#42a5f5'};--pants:${pants?.[4]||'#455a64'};--shoe:${shoes?.[4]||'#e53935'}"><div class="bh-cape">${cape?'🦸':''}</div><div class="bh-hair">${hair?.[2]||'🧑'}</div><div class="bh-face">${mask?.[2]||face?.[2]||'😊'}</div><div class="bh-body">${costume?.[2]||'👕'}<i>${emblem?.[2]||''}</i></div><div class="bh-hands">${gloves?'🧤':''}</div><div class="bh-belt">${belt?.[2]||''}</div><div class="bh-pants">${pants?.[2]||'🩳'}</div><div class="bh-shoes">${shoes?.[2]||'👟'}</div></div>`};
  Wardrobe.render=function(){ensure();const t=T(),category=Player.data.wardrobeCategory,isGirl=Player.data.outfit.body==='Girl Hero',categoryItems=category==='pets'?pets:catalog.filter(x=>x[0]===category&&(category!=='costume'||x[5]===(isGirl?'girl':'boy'))),categories=['body','face','boyHair','girlHair','mask','hat','glasses','shoes','gloves','emblem','necklace','belt','costume','pants','cape','wings','weapon','backpack','aura','background','pose','pets'];const cards=category==='pets'?categoryItems.map(x=>`<article class="book-item"><span>${x[1]}</span><b>${x[0]}</b><small>🪙 ${x[2]}</small><button onclick="Wardrobe.pet('${x[0]}','${x[1]}',${x[2]})">${Player.data.inventory.includes(x[0])?t.wear:t.buy}</button></article>`).join(''):categoryItems.map(x=>{const owned=Player.data.inventory.includes(x[1]),on=Player.data.outfit[x[0]]===x[1],art=x[0]==='costume'?'<span class="outfit-art" aria-hidden="true"></span>':x[2];return `<article class="book-item outfit-card outfit-${x[1].toLowerCase().replace(/[^a-z0-9]+/g,'-')} ${on?'selected':''}"><span>${art}</span><b>${x[1]}</b><small>🪙 ${x[3]}</small><button ${on?'disabled':`onclick="Wardrobe.${owned?'equip':'buy'}('${x[1]}')"`}>${on?t.on:owned?t.wear:t.buy}</button></article>`}).join('');return `<div class="custom-book"><section class="book-left"><div class="book-money"><span>⚡ ${t.xp}: ${Player.data.totalXp}</span><span>🪙 ${t.coins}: ${Player.data.coins}</span></div>${this.figure('book-large')}<h2>${Player.data.name}</h2>${Player.data.pet?`<div class="book-pet">${Player.data.pet}</div>`:''}</section><section class="book-right"><div class="book-head"><button class="book-home" data-page="home">← ${t.back}</button><h1>${t.title}</h1></div><h2>🦸 ${t.hero}</h2><nav class="book-categories">${categories.map(c=>`<button class="${category===c?'active':''}" onclick="Wardrobe.category('${c}')">${t[c]||({hat:'Hats & Crowns',glasses:'Glasses',wings:'Wings',weapon:'Weapons & Tools',backpack:'Backpacks',necklace:'Necklaces',aura:'Auras',background:'Backgrounds',pose:'Hero Poses'}[c])}</button>`).join('')}</nav><div class="book-items">${cards}</div></section></div>`};
  Wardrobe.render=function improvedWardrobe(){
    ensure();
    const t=T(),category=Player.data.wardrobeCategory,filter=Player.data.wardrobeFilter||'all',isGirl=Player.data.outfit.body==='Girl Hero';
    const categories=['body','face','boyHair','girlHair','mask','hat','glasses','shoes','gloves','emblem','necklace','belt','costume','pants','cape','wings','weapon','backpack','aura','background','pose','pets'];
    let categoryItems=category==='pets'?pets:catalog.filter(item=>item[0]===category);
    if(category==='costume')categoryItems=categoryItems.filter(item=>item[5]===((filter==='girl'||filter==='boy')?filter:(isGirl?'girl':'boy')));
    if(filter==='owned')categoryItems=categoryItems.filter(item=>Player.data.inventory.includes(item[category==='pets'?0:1]));
    if(filter==='locked')categoryItems=categoryItems.filter(item=>!Player.data.inventory.includes(item[category==='pets'?0:1]));
    if(filter==='boy'&&category==='girlHair')categoryItems=[];
    if(filter==='girl'&&category==='boyHair')categoryItems=[];
    const removeCard=`<article class="book-item remove-card"><span>✕</span><b>Remove Item</b><small>Clear this category</small><button onclick="Wardrobe.removeItem('${category}')">Remove</button></article>`;
    const cards=category==='pets'?categoryItems.map(item=>{const owned=Player.data.inventory.includes(item[0]),equipped=Player.data.petName===item[0];return `<article class="book-item ${equipped?'selected':''}"><div class="item-badges"><i class="${equipped?'equipped':owned?'owned':'new'}">${equipped?'Equipped':owned?'Owned':'New'}</i>${!owned?'<i class="locked">Locked</i>':''}</div><span>${item[1]}</span><b>${item[0]}</b><small>🪙 ${item[2]}</small><button class="${equipped?'unequip-button':''}" onclick="${equipped?"Wardrobe.removeItem('pets')":`Wardrobe.pet('${item[0]}','${item[1]}',${item[2]})`}">${equipped?'Unequip':owned?t.wear:t.buy}</button></article>`}).join(''):categoryItems.map(item=>{const owned=Player.data.inventory.includes(item[1]),equipped=Player.data.outfit[item[0]]===item[1],art=item[0]==='costume'?'<span class="outfit-art" aria-hidden="true"></span>':item[2];return `<article class="book-item outfit-card outfit-${item[1].toLowerCase().replace(/[^a-z0-9]+/g,'-')} ${equipped?'selected':''}"><div class="item-badges"><i class="${equipped?'equipped':owned?'owned':'new'}">${equipped?'Equipped':owned?'Owned':'New'}</i>${!owned?'<i class="locked">Locked</i>':''}</div><span>${art}</span><b>${item[1]}</b><small>🪙 ${item[3]}</small><button class="${equipped?'unequip-button':''}" onclick="${equipped?`Wardrobe.removeItem('${item[0]}')`:`Wardrobe.${owned?'equip':'buy'}('${item[1]}')`}">${equipped?'Unequip':owned?t.wear:t.buy}</button></article>`}).join('');
    const filters=[['all','All'],['boy','Boy'],['girl','Girl'],['owned','Owned'],['locked','Locked']];
    return `<div class="custom-book"><section class="book-left"><div class="book-money"><span>⚡ ${t.xp}: ${Player.data.totalXp}</span><span>🪙 ${t.coins}: ${Player.data.coins}</span></div>${this.figure('book-large')}<h2>${Player.data.name}</h2>${Player.data.pet?`<div class="book-pet">${Player.data.pet}</div>`:''}<div class="hero-quick-actions"><button class="randomize-hero" onclick="Wardrobe.randomize()">🎲 Randomize Owned</button><button class="remove-all-hero" onclick="Wardrobe.removeAll()">✕ Remove All</button></div></section><section class="book-right"><div class="book-head"><button class="book-home" data-page="home">← ${t.back}</button><h1>${t.title}</h1></div><h2>🦸 ${t.hero}</h2><nav class="book-categories">${categories.map(c=>`<button class="${category===c?'active':''}" onclick="Wardrobe.category('${c}')">${t[c]||({hat:'Hats & Crowns',glasses:'Glasses',wings:'Wings',weapon:'Weapons & Tools',backpack:'Backpacks',necklace:'Necklaces',aura:'Auras',background:'Backgrounds',pose:'Hero Poses'}[c])}</button>`).join('')}</nav><div class="wardrobe-filters">${filters.map(([id,label])=>`<button class="${filter===id?'active':''}" onclick="Wardrobe.setFilter('${id}')">${label}</button>`).join('')}</div><div class="book-items">${removeCard}${cards||'<p class="empty-filter">No items match this filter.</p>'}</div></section></div>`;
  };
  const rawBookRender=Wardrobe.render.bind(Wardrobe);
  Wardrobe.render=function localizedBook(){let html=rawBookRender(),languageId=language();if(languageId==='en')return html;const names={fr:{'Warm Body':'Corps clair','Golden Body':'Corps doré','Happy Face':'Visage joyeux','Brave Face':'Visage courageux','Hero Hair':'Coiffure du héros','Spiky Hair':'Cheveux hérissés','Explorer Hair':'Coiffure exploratrice','Royal Hair':'Coiffure royale','Ninja Mask':'Masque ninja','Robot Mask':'Masque robot','Red Sneakers':'Baskets rouges','Star Boots':'Bottes étoilées','Power Gloves':'Gants de puissance','Ice Gloves':'Gants de glace','Star Emblem':'Emblème étoile','Dragon Emblem':'Emblème dragon','Adventure Belt':'Ceinture d’aventure','Champion Belt':'Ceinture de champion','Sky T-Shirt':'T-shirt du ciel','Forest Hoodie':'Sweat de la forêt','Galaxy Jacket':'Veste galaxie','Adventure Shorts':'Short d’aventure','Knight Pants':'Pantalon de chevalier','Shadow Cape':'Cape de l’ombre','Royal Cape':'Cape royale',Dog:'Chien',Cat:'Chat','Baby Dragon':'Bébé dragon','Mini Robot':'Mini robot',Fox:'Renard',Owl:'Hibou'},ar:{'Warm Body':'بشرة فاتحة','Golden Body':'بشرة ذهبية','Happy Face':'وجه سعيد','Brave Face':'وجه شجاع','Hero Hair':'شعر البطل','Spiky Hair':'شعر شائك','Explorer Hair':'شعر المستكشفة','Royal Hair':'شعر ملكي','Ninja Mask':'قناع النينجا','Robot Mask':'قناع الروبوت','Red Sneakers':'حذاء رياضي أحمر','Star Boots':'حذاء النجوم','Power Gloves':'قفازات القوة','Ice Gloves':'قفازات الجليد','Star Emblem':'شعار النجمة','Dragon Emblem':'شعار التنين','Adventure Belt':'حزام المغامرة','Champion Belt':'حزام البطل','Sky T-Shirt':'قميص السماء','Forest Hoodie':'سترة الغابة','Galaxy Jacket':'سترة المجرة','Adventure Shorts':'سروال مغامرة قصير','Knight Pants':'سروال الفارس','Shadow Cape':'عباءة الظلال','Royal Cape':'العباءة الملكية',Dog:'كلب',Cat:'قطة','Baby Dragon':'تنين صغير','Mini Robot':'روبوت صغير',Fox:'ثعلب',Owl:'بومة'}}[languageId];Object.entries(names||{}).forEach(([from,to])=>{html=html.split(`>${from}<`).join(`>${to}<`)});return html};
})();
