// A spoken, once-per-profile introduction for brand-new players.
(() => {
  const copy={
    en:[['👋','Hello! Welcome to Math Academy. I am your guide, and I will show you around.'],['🗺️','This is your adventure map. Choose a world to practise maths, fractions, typing, memory, and more.'],['🎮','In the Games library, every correct answer earns experience, coins, and rewards for your hero.'],['👕','Visit Hero to customise your character and collect pets and outfits. The Shop is where you spend coins you earned by learning.'],['👤','Your Profile shows your progress. In Settings, you can change the language, sound, difficulty, and account. You are ready to begin your adventure!']],
    fr:[['👋','Bonjour ! Bienvenue à Math Academy. Je suis ton guide et je vais te faire visiter.'],['🗺️','Voici ta carte d’aventure. Choisis un monde pour t’entraîner en maths, fractions, frappe, mémoire et plus encore.'],['🎮','Dans la bibliothèque de jeux, chaque bonne réponse rapporte de l’expérience, des pièces et des récompenses.'],['👕','Va dans Héros pour personnaliser ton personnage et collectionner des compagnons et des tenues. La boutique permet de dépenser les pièces gagnées.'],['👤','Ton profil montre tes progrès. Dans les paramètres, tu peux changer la langue, le son, la difficulté et le compte. Tu es prêt à commencer ton aventure !']],
    ar:[['👋','مرحبًا! أهلًا بك في أكاديمية الرياضيات. أنا دليلك وسأريك المكان.'],['🗺️','هذه خريطة مغامرتك. اختر عالمًا للتدرب على الرياضيات والكسور والكتابة والذاكرة والمزيد.'],['🎮','في مكتبة الألعاب، كل إجابة صحيحة تمنح بطلك خبرة وعملات ومكافآت.'],['👕','اذهب إلى البطل لتخصيص شخصيتك وجمع الرفاق والأزياء. المتجر هو مكان إنفاق العملات التي تكسبها بالتعلّم.'],['👤','يعرض ملفك الشخصي تقدمك. في الإعدادات يمكنك تغيير اللغة والصوت والصعوبة والحساب. أنت جاهز لبدء مغامرتك!']]
  };
  const labels={en:{title:'Your Math Academy Guide',skip:'Skip guide',next:'Next',start:'Start Adventure',heard:'🔊 Your guide is speaking'},fr:{title:'Ton guide Math Academy',skip:'Passer le guide',next:'Suivant',start:'Commencer l’aventure',heard:'🔊 Ton guide parle'},ar:{title:'دليل أكاديمية الرياضيات',skip:'تخطي الدليل',next:'التالي',start:'ابدأ المغامرة',heard:'🔊 دليلك يتحدث'}};
  const repeatLabel={en:'🔊 Hear again',fr:'🔊 Réécouter',ar:'🔊 استمع مجددًا'};
  const guidePages=['home','map','games','wardrobe','settings'];
  let step=0,advanceTimer=null;
  const language=()=>['en','fr','ar'].includes(Player.data.settings.guideLanguage)?Player.data.settings.guideLanguage:(['en','fr','ar'].includes(Player.data.settings.language)?Player.data.settings.language:'en');
  const stopTalking=()=>window.speechSynthesis?.cancel();
  const speak=(text,onFinish=()=>{})=>{stopTalking();if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){onFinish();return}const utterance=new SpeechSynthesisUtterance(text),voiceLanguage={en:'en',fr:'fr',ar:'ar'}[language()],gender=Player.data.gender||'boy',voices=speechSynthesis.getVoices().filter(item=>item.lang.toLowerCase().startsWith(voiceLanguage)),female=/female|woman|zira|susan|samantha|victoria|hazel|aria|ava|allison|serena|salli|joanna|kendra|kimberly|ivy|emma|olivia|linda|heera|kalpana/i,male=/male|man|david|mark|james|daniel|alex|george|guy|thomas|brian|fred/i;utterance.lang={en:'en-US',fr:'fr-FR',ar:'ar-SA'}[language()];utterance.rate=gender==='girl'?.98:.88;utterance.pitch=gender==='girl'?1.45:.82;utterance.volume=1;const preferred=gender==='girl'?female:male,avoid=gender==='girl'?male:female,voice=voices.find(item=>preferred.test(item.name))||voices.find(item=>!avoid.test(item.name))||voices[0];if(voice)utterance.voice=voice;utterance.onend=onFinish;utterance.onerror=onFinish;speechSynthesis.resume();speechSynthesis.speak(utterance)};
  const finish=()=>{clearTimeout(advanceTimer);stopTalking();document.body.classList.remove('guide-active');Player.data.welcomeGuideComplete=true;Player.save();document.querySelector('#modal').classList.add('hidden');App.navigate('home')};
  const scheduleAdvance=()=>{clearTimeout(advanceTimer);advanceTimer=setTimeout(()=>WelcomeGuide.next(),24000)};
  const renderSetup=()=>{const modal=document.querySelector('#modal'),gameLanguage=Player.data.settings.language||'en',gender=Player.data.gender||'boy';document.body.classList.add('guide-active');modal.innerHTML=`<section class="dialog card pop welcome-guide guide-language-setup" role="document"><div class="guide-icon">🌐</div><h2>Choose your setup</h2><p class="guide-message">Choose your hero, your game language, and the language your guide will speak.</p><div class="guide-gender"><label><input type="radio" name="guide-gender" value="boy" ${gender==='boy'?'checked':''}><span>👦<b>Boy</b></span></label><label><input type="radio" name="guide-gender" value="girl" ${gender==='girl'?'checked':''}><span>👧<b>Girl</b></span></label></div><label>Game language<select id="guide-game-language" class="text-input"><option value="en" ${gameLanguage==='en'?'selected':''}>English</option><option value="fr">Français</option><option value="ar">العربية</option></select></label><label>Guide language<select id="guide-voice-language" class="text-input"><option value="en">English</option><option value="fr">Français</option><option value="ar">العربية</option></select></label><button class="btn gold guide-next" type="button" onclick="WelcomeGuide.saveLanguages()">Start the guide</button></section>`;modal.classList.remove('hidden')};
  const render=()=>{const lang=language(),words=copy[lang][step],label=labels[lang],modal=document.querySelector('#modal');App.navigate(guidePages[step]);modal.innerHTML=`<section class="dialog card pop welcome-guide" role="document"><button class="btn ghost guide-skip" type="button" onclick="WelcomeGuide.skip()">${label.skip}</button><div class="guide-icon">${words[0]}<i></i><i></i><i></i></div><div class="guide-step">${step+1} / ${copy[lang].length}</div><h2>${label.title}</h2><p class="guide-message">${words[1]}</p></section>`;modal.classList.remove('hidden');scheduleAdvance();speak(words[1],()=>{if(!document.body.classList.contains('guide-active'))return;clearTimeout(advanceTimer);advanceTimer=setTimeout(()=>WelcomeGuide.next(),450)})};
  const preventBackgroundInput=event=>{if(document.body.classList.contains('guide-active'))event.preventDefault()};
  window.addEventListener('wheel',preventBackgroundInput,{passive:false});
  window.addEventListener('touchmove',preventBackgroundInput,{passive:false});
  window.addEventListener('keydown',preventBackgroundInput);
  window.WelcomeGuide={setup(){if(!Player.data.name||Player.data.welcomeGuideComplete)return;renderSetup()},saveLanguages(){const game=document.querySelector('#guide-game-language')?.value,guide=document.querySelector('#guide-voice-language')?.value,gender=document.querySelector('input[name="guide-gender"]:checked')?.value;Player.data.settings.language=['en','fr','ar'].includes(game)?game:'en';Player.data.settings.guideLanguage=['en','fr','ar'].includes(guide)?guide:Player.data.settings.language;Player.data.gender=gender==='girl'?'girl':'boy';Player.data.outfit||={};Player.data.outfit.body=Player.data.gender==='girl'?'Girl Hero':'Boy Hero';Player.data.outfitBaseInitialized=true;Player.save();window.BrainQuestI18n?.apply();this.start()},start(){if(!Player.data.name||Player.data.welcomeGuideComplete)return;if(!Player.data.settings.guideLanguage)return this.setup();document.body.classList.add('guide-active');step=0;render()},next(){if(Player.data.welcomeGuideComplete)return;if(step>=copy[language()].length-1)return finish();step++;render()},repeat(){render()},skip:finish};
})();
